### PR TITLE
Feature/partners

### PR DESCRIPTION
**Pull request by surfer19**

### CODE REVIEW

**Comment by marusinm** [comment]
I would add also the logo of Copernicus Accelerator. What do you say @rpitonak @mjavorka 
https://images.app.goo.gl/tWkoXGjQZQ4WCWXH6

**Comment by surfer19** [comment]
I think you should ask for permission to use logo on web

**Comment by marusinm** [comment]
On the other hand, do we have permission for TechNest and S.A.B logo when you have already implemented it?

**Comment by surfer19** [comment]
@marusinm yes Vasek confirmed it right @rpitonak ?

**Pull request merged**
